<?php

return [

    'candidates' => [
        // presidentiables
        [
            'name' => 'ABELLA, ERNIE',
            'picture' => 'https://eboto.ph/uploads/2022/02/39aaa4e39c921ca8506d12000fb614e7.png',
            'profile_url' => 'https://eboto.ph/candidate/ernesto-abella/fast-facts',
            'party' => 'INDEPENDENT',
            'ballot_number' => 1,
            'position' => 'president',
        ],
        [
            'name' => 'DE GUZMAN, LEODY',
            'picture' => 'https://eboto.ph/uploads/2022/02/7f3680303c5aea63cabba2fa7c89e95b.png',
            'profile_url' => 'https://eboto.ph/candidate/leodigario-de-guzman/fast-facts',
            'party' => 'PARTIDO LAKAS NG MASA',
            'ballot_number' => 2,
            'position' => 'president',
        ],
        [
            'name' => 'DOMAGOSO, ISKO MORENO',
            'picture' => 'https://csranker.com/uploads/election/1630571043.png',
            'profile_url' => 'https://eboto.ph/candidate/isko-moreno/fast-facts',
            'party' => 'AKSYON DEMOKRATIKO',
            'ballot_number' => 3,
            'position' => 'president',
        ],
        [
            'name' => 'GONZALES, NORBERTO',
            'picture' => 'https://eboto.ph/uploads/2022/02/fcdb14dfd11e30e9169e88dba3b76d72.png',
            'profile_url' => 'https://eboto.ph/candidate/norberto-gonzales/fast-facts',
            'party' => 'PARTIDO DEMOKTRATIKO SOSYALISTA PILIPINAS',
            'ballot_number' => 4,
            'position' => 'president',
    ],
        [
            'name' => 'LACSON, PING',
            'picture' => 'https://eboto.ph/uploads/2021/11/Ping-Lacson2.jpg',
            'profile_url' => 'https://eboto.ph/candidate/panfilo-lacson/fast-facts',
            'party' => 'PARTIDO PARA SA DEMOKRATIKONG REPORMA',
            'ballot_number' => 5,
            'position' => 'president',
        ],
        [
            'name' => 'MANGONDATO, FAISAL',
            'picture' => 'https://eboto.ph/uploads/2022/02/954f1b07aad91106d584552330c4f06e.png',
            'profile_url' => 'https://eboto.ph/candidate/faisal-mangondato/fast-facts',
            'party' => 'KATIPUNAN NG KAMALAYANG KAYUMANGGI',
            'ballot_number' => 6,
            'position' => 'president',
        ],
        [
            'name' => 'MARCOS, BONGBONG',
            'picture' => 'https://i1.wp.com/www.filipinoscribe.com/wp-content/uploads/2016/03/bongbong-marcos-vice-president.jpg?ssl=1',
            'profile_url' => 'https://eboto.ph/candidate/ferdinand-marcos-jr/fast-facts',
            'party' => 'PARTIDO FEDERAL NG PILIPINAS',
            'ballot_number' => 7,
            'position' => 'president',
        ],
        [
            'name' => 'MONTEMAYOR, JOSE JR.',
            'picture' => 'https://eboto.ph/uploads/2022/02/54107e3db6aac244a1776a2c21adf946.jpg',
            'profile_url' => 'https://eboto.ph/candidate/jose-montemayor/fast-facts',
            'party' => 'DEMOCRACTIC PARTY OF THE PHILIPPINES',
            'ballot_number' => 8,
            'position' => 'president',
        ],
        [
            'name' => 'PACQUIAO, MANNY PACMAN',
            'picture' => 'https://eboto.ph/uploads/2022/02/2e628d284761555840ec56926c528cb0.png',
            'profile_url' => 'https://eboto.ph/candidate/emmanuel-pacquiao/fast-facts',
            'party' => 'ABAG PROMDI',
            'ballot_number' => 9,
            'position' => 'president',
        ],
        [
            'name' => 'ROBREDO, LENI',
            'picture' => '/images/Leni_Robredo.png',
            'profile_url' => 'https://eboto.ph/candidate/maria-leonor-robredo/fast-facts',
            'party' => 'INDEPENDENT',
            'ballot_number' => 10,
            'position' => 'president',
        ],

        // vice presidents
        [
            'name' => 'ATIENZA, LITO',
            'picture' => 'https://eboto.ph/uploads/2022/01/3b862e04c8220ce004af920e51f1a7bb.jpg',
            'profile_url' => 'https://eboto.ph/candidate/litoatienza/fast-facts',
            'party' => 'ABAG PROMDI',
            'ballot_number' => 1,
            'position' => 'vice_president',
        ],
        [
            'name' => 'BELLO, WALDEN',
            'picture' => 'https://eboto.ph/uploads/2022/02/3414d964ba9db2d88aa4f1e9dfb4653e.png',
            'profile_url' => 'https://eboto.ph/candidate/walden-bello/fast-facts',
            'party' => 'PARTIDO LAKAS NG MASA',
            'ballot_number' => 2,
            'position' => 'vice_president',
        ],
        [
            'name' => 'DAVID, RIZALITO',
            'picture' => 'https://eboto.ph/uploads/2022/01/1691b6dbbfb6d050ddac57fbd820b82a.jpg',
            'profile_url' => 'https://eboto.ph/candidate/rizalito-david/fast-facts',
            'party' => 'DEMOCRACTIC PARTY OF THE PHILIPPINES',
            'ballot_number' => 3,
            'position' => 'vice_president',
        ],
        [
            'name' => 'DUTERTE, SARA',
            'picture' => 'https://mb.com.ph/wp-content/uploads/2022/01/SARA-DUTERTE.jpg',
            'profile_url' => 'https://eboto.ph/candidate/sara-duterte-carpio/fast-facts',
            'party' => 'LAKAS CHRISTIAN MUSLIM DEMOCRATS',
            'ballot_number' => 4,
            'position' => 'vice_president',
        ],
        [
            'name' => 'LOPEZ, MANNY SD',
            'picture' => 'https://eboto.ph/uploads/2022/02/558020f97fd216166f099bdba5319891.png',
            'profile_url' => 'https://eboto.ph/candidate/manny-lopez/fast-facts',
            'party' => 'WORKERS AND PEASANTS PARTY',
            'ballot_number' => 5,
            'position' => 'vice_president',
        ],
        [
            'name' => 'ONG, DOC WILLIE',
            'picture' => 'https://eboto.ph/uploads/2022/01/7355a733c06051c1ffc169295730ec41.jpg',
            'profile_url' => 'https://eboto.ph/candidate/willie-ong/fast-facts',
            'party' => 'AKSYON DEMOKRATIKO',
            'ballot_number' => 6,
            'position' => 'vice_president',
        ],
        [
            'name' => 'PANGILINAN, KIKO',
            'picture' => 'https://eboto.ph/uploads/2022/01/ba986c9d44d85aa68fb0e38d6f94f681.jpg',
            'profile_url' => 'https://eboto.ph/candidate/kiko-pangilinan/fast-facts',
            'party' => 'LIBERAL PARTY',
            'ballot_number' => 7,
            'position' => 'vice_president',
        ],
        [
            'name' => 'SERAPIO, CARLOS',
            'picture' => 'https://eboto.ph/uploads/2022/02/3b6ab195270ea4fd616735992396dfaf.png',
            'profile_url' => 'https://eboto.ph/candidate/carlos-serapio/fast-facts',
            'party' => 'KATIPUNAN NG KAMALAYANG KAYUMANGGI',
            'ballot_number' => 8,
            'position' => 'vice_president',
        ],
        [
            'name' => 'SOTTO, VICENTE TITO',
            'picture' => 'https://eboto.ph/uploads/2022/01/23144b237624482d2c8d3d08633b980e.jpg',
            'profile_url' => 'https://eboto.ph/candidate/vicente-castelo-sotto/fast-facts',
            'party' => "NATIONALIST PEOPLE'S COALITION",
            'ballot_number' => 9,
            'position' => 'vice_president',
        ],

        // senators
        [
            'name' => 'AFUANG, ABNER',
            'picture' => 'https://eboto.ph/uploads/2022/02/82e9bff9eaf5780d1f95d547f1b3c8fc.jpg',
            'profile_url' => 'https://eboto.ph/candidate/afuang/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 1,
            'position' => 'senator',
        ],
        [
            'name' => 'ALBANI, IBRAHIM ',
            'picture' => 'https://eboto.ph/uploads/2022/02/73c2544c845a17dfde8488df851e5825.jpg',
            'profile_url' => 'https://eboto.ph/candidate/ibrahim-albani/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'WORKERS AND PEASANTS PARTY (LABOR PARTY PHILIPPINES)',
            'ballot_number' => 2,
            'position' => 'senator',
        ],
        [
            'name' => 'ARRANZA, MANG JESS',
            'picture' => '/images/jess_arranza.png',
            'profile_url' => 'https://eboto.ph/candidate/jesus-arranza/issue-rundown',
            'party' => 'INDEPENDENT',
            'ballot_number' => 3,
            'position' => 'senator',
        ],
        [
            'name' => 'BAGUILAT, TEDDY',
            'picture' => 'https://eboto.ph/uploads/2022/02/68d28aa92eb2d30645f5370dbf668c97.jpg',
            'profile_url' => 'https://eboto.ph/candidate/teddybaguilat/issue-rundown',
            'party' => 'LIBERAL PARTY',
            'ballot_number' => 4,
            'position' => 'senator',
        ],
        [
            'name' => 'BAILEN, AGNES',
            'picture' => 'https://eboto.ph/uploads/2022/02/091feac361364e8a48014c558469e703.jpg',
            'profile_url' => 'https://eboto.ph/candidate/agnes-bailen/issue-rundown',
            'party' => 'INDEPENDENT',
            'ballot_number' => 5,
            'position' => 'senator',
        ],
        [
            'name' => 'BALITA, CARL',
            'picture' => 'https://eboto.ph/uploads/2022/02/d7ea5548a77904fd4166e30d013cc756.jpg',
            'profile_url' => 'https://eboto.ph/candidate/carl-espino-balita/issue-rundown',
            'party' => 'AKSYON DEMOKRATIKO',
            'ballot_number' => 6,
            'position' => 'senator',
        ],
        [
            'name' => 'BARBO, LUTZ',
            'picture' => '/images/barbo_lutz.png',
            'profile_url' => 'https://eboto.ph/candidate/lutz-barbo/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'PDP-LABAN',
            'ballot_number' => 7,
            'position' => 'senator',
        ],
        [
            'name' => 'BAUTISTA, HERBERT BISTEK',
            'picture' => 'https://eboto.ph/uploads/2022/02/34cb050ec76e9c11ee7adffd87eee07f.jpg',
            'profile_url' => 'https://eboto.ph/candidate/herbert-maclang-bautista/issue-rundown',
            'party' => "NATIONALIST PEOPLE'S COALITION",
            'ballot_number' => 8,
            'position' => 'senator',
        ],
        [
            'name' => 'BELGICA, GRECO',
            'picture' => 'https://2.bp.blogspot.com/-Y07H2ewV9_o/VtLpUS6UBMI/AAAAAAAACBQ/r9FSLLGicow/s1600/12745469_456748997863140_1356750074435947772_n.jpg',
            'profile_url' => 'https://eboto.ph/candidate/greco-banta-belgica/issue-rundown',
            'party' => 'PEDERALISMO NG DUGONG DAKILANG SAMAHAN',
            'ballot_number' => 9,
            'position' => 'senator',
        ],
        [
            'name' => 'BELLO, SILVESTRE JR.',
            'picture' => 'images/silvestre_bello.png',
            'profile_url' => 'https://ph.rappler.com/elections/2022/candidates/Silvestre-Bello-Jr',
            'party' => 'PDP-LABAN',
            'ballot_number' => 10,
            'position' => 'senator',
        ],
        [
            'name' => 'BINAY, JOJO',
            'picture' => 'https://eboto.ph/uploads/2022/02/39333da6365f330eb55d638e35f8ba07.JPG',
            'profile_url' => 'https://eboto.ph/candidate/jejomarbinay/issue-rundown',
            'party' => 'UNITED NATIONALIST ALLIANCE',
            'ballot_number' => 11,
            'position' => 'senator',
        ],
        [
            'name' => 'CABONEGRO, ROY',
            'picture' => 'images/roy_cabognero.png',
            'profile_url' => 'https://eboto.ph/candidate/roy-cabonegro/issue-rundown',
            'party' => 'PARTIDO LAKAS NG MASA',
            'ballot_number' => 12,
            'position' => 'senator',
        ],
        [
            'name' => 'CASTRICIONES, BRO JOHN',
            'picture' => 'https://eboto.ph/uploads/2022/02/8778d5eee0a429ebf12ae7969946b83d.jpg',
            'profile_url' => 'https://eboto.ph/candidate/john-castriciones/issue-rundown',
            'party' => 'PDP-LABAN',
            'ballot_number' => 13,
            'position' => 'senator',
        ],
        [
            'name' => 'CAYETANO, ALAN PETER',
            'picture' => 'https://eboto.ph/uploads/2022/02/d415b45535b556d526dfd84fd0864126.jpg',
            'profile_url' => 'https://eboto.ph/candidate/alan-cayetano/issue-rundown',
            'party' => 'INDEPENDENT',
            'ballot_number' => 14,
            'position' => 'senator',
        ],
        [
            'name' => 'CHAVEZ, MELCHOR',
            'picture' => 'https://eboto.ph/uploads/2022/02/8e285e914df2fe39076e10e0b53ab40f.JPG',
            'profile_url' => 'https://eboto.ph/candidate/melchorchavez/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'WORKERS AND PEASANTS PARTY (LABOR PARTY PHILIPPINES)',
            'ballot_number' => 15,
            'position' => 'senator',
        ],
        [
            'name' => 'COLMENARES, NERI',
            'picture' => 'https://eboto.ph/uploads/2022/02/5a3b37cb07ce7cc23e45154e6898fff5.jpg',
            'profile_url' => 'https://eboto.ph/candidate/nericolmenares/issue-rundown',
            'party' => 'MAKABAYANG KOALISYON NG MAMAMAYAN',
            'ballot_number' => 16,
            'position' => 'senator',
        ],
        [
            'name' => "D'ANGELO, DAVID",
            'picture' => 'https://eboto.ph/uploads/2022/02/406e04780bc90695959c701debf8412c.jpg',
            'profile_url' => 'https://eboto.ph/candidate/daviddangelo/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'PARTIDO LAKAS NG MASA',
            'ballot_number' => 17,
            'position' => 'senator',
        ],
        [
            'name' => 'DE LIMA, LEILA',
            'picture' => 'https://eboto.ph/uploads/2022/02/ce2d420c7c941dcfbd48543bfcd681ce.jpg',
            'profile_url' => 'https://eboto.ph/candidate/leila-delima/issue-rundown',
            'party' => 'LIBERAL PARTY',
            'ballot_number' => 18,
            'position' => 'senator',
        ],
        [
            'name' => 'DEL ROSARIO, MONSOUR',
            'picture' => 'https://eboto.ph/uploads/2022/02/9d29895f252e42ae26e1dbd598aac398.jpg',
            'profile_url' => 'https://eboto.ph/candidate/monsour-delrosario/fast-facts',
            'party' => 'PARTIDO PARA SA DEMOKRATIKONG REPORMA',
            'ballot_number' => 19,
            'position' => 'senator',
        ],
        [
            'name' => 'DIAZ, DING',
            'picture' => 'https://eboto.ph/uploads/2022/02/369b9619c702d6f1b09566aa99740bfd.jpg',
            'profile_url' => 'https://eboto.ph/candidate/ding-diaz/issue-rundown',
            'party' => 'PARTIDO PILIPINO SA PAGBABAGO',
            'ballot_number' => 20,
            'position' => 'senator',
        ],
        [
            'name' => 'DIOKNO, CHEL',
            'picture' => 'https://eboto.ph/uploads/2022/02/35616bfcaf4a9eab2153b7d81844d078.jpg',
            'profile_url' => 'https://eboto.ph/candidate/chel-icasiano-diokno/issue-rundown',
            'party' => 'KATIPUNAN NG NAGKAKAISANG PILIPINO',
            'ballot_number' => 21,
            'position' => 'senator',
        ],
        [
            'name' => 'EJERCITO, JV ESTRADA',
            'picture' => 'https://eboto.ph/uploads/2022/02/4d1683d937e5f7a37d9c413877ad1964.jpg',
            'profile_url' => 'https://eboto.ph/candidate/jvejercito/issue-rundown',
            'party' => "NATIONALIST PEOPLE'S COALITION",
            'ballot_number' => 22,
            'position' => 'senator',
        ],
        [
            'name' => 'ELEAZAR, GEN. GUILLERMO',
            'picture' => 'https://eboto.ph/uploads/2022/02/8bc3a3d27ed1ab728e67fed7551fe4be.jpg',
            'profile_url' => 'https://eboto.ph/candidate/guillermo-tolentino-eleazar/issue-rundown',
            'party' => 'PARTIDO PARA SA DEMOKRATIKONG REPORMA',
            'ballot_number' => 23,
            'position' => 'senator',
        ],
        [
            'name' => 'EREÑO, BRO. ERNIE',
            'picture' => 'https://eboto.ph/uploads/2022/02/00eb2c281a48bd303dea2d115b9fc61f.jpeg',
            'profile_url' => 'https://eboto.ph/candidate/ernie-ereno/issue-rundown',
            'party' => 'PARTIDO MAHARLIKA',
            'ballot_number' => 24,
            'position' => 'senator',
        ],
        [
            'name' => 'ESCUDERO, CHIZ',
            'picture' => 'https://eboto.ph/uploads/2022/02/8802bed3e1e4c140f6010915a5b9acee.jpg',
            'profile_url' => 'https://eboto.ph/candidate/francischiz-escudero/issue-rundown?scrollto=candidate-info-tab',
            'party' => "NATIONALIST PEOPLE'S COALITION",
            'ballot_number' => 25,
            'position' => 'senator',
        ],
        [
            'name' => 'ESPIRITU, LUKE',
            'picture' => 'https://newsinfo.inquirer.net/files/2022/03/257899.jpeg',
            'profile_url' => 'https://eboto.ph/candidate/atty-luke-espiritu/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'PARTIDO LAKAS NG MASA',
            'ballot_number' => 26,
            'position' => 'senator',
        ],
        [
            'name' => 'ESTRADA, JINGGOY',
            'picture' => 'https://eboto.ph/uploads/2022/02/3e85922d82f719b5b8b112b019773670.jpg',
            'profile_url' => 'https://eboto.ph/candidate/jinggoy-estrada/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'PWERSA NG MASANG PILIPINO',
            'ballot_number' => 27,
            'position' => 'senator',
        ],
        [
            'name' => 'FALCONE, BAL FALCON',
            'picture' => 'https://eboto.ph/uploads/2022/03/aaf660036193026b206c8d63aea0f333.jpg',
            'profile_url' => 'https://eboto.ph/candidate/bal-falcon/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'DEMOCRATIC PARTY OF THE PHILIPPINES',
            'ballot_number' => 28,
            'position' => 'senator',
        ],
        [
            'name' => 'GADON, LARRY',
            'picture' => 'https://eboto.ph/uploads/2022/02/8b75dcfd5e8d7bf59e72d3ba81e728c5.jpg',
            'profile_url' => 'https://eboto.ph/candidate/larrygadon/issue-rundown',
            'party' => 'KILUSANG BAGONG LIPUNAN',
            'ballot_number' => 29,
            'position' => 'senator',
        ],
        [
            'name' => 'GATCHALIAN, WIN',
            'picture' => 'https://eboto.ph/uploads/2022/02/e6c340bbce507c2e4dc46eded5b3e729.jpg',
            'profile_url' => 'https://eboto.ph/candidate/win-gatchalian/issue-rundown',
            'party' => "NATIONALIST PEOPLE'S COALITION",
            'ballot_number' => 30,
            'position' => 'senator',
        ],
        [
            'name' => 'GORDON, WOW DICK',
            'picture' => 'https://eboto.ph/uploads/2022/02/25f8323243418f23eacca0547272178d.JPG',
            'profile_url' => 'https://eboto.ph/candidate/dick-gordon/issue-rundown',
            'party' => 'BAGUMBAYAN VOLUNTEERS FOR A NEW PHILIPPINES',
            'ballot_number' => 31,
            'position' => 'senator',
        ],
        [
            'name' => 'GUTOC, SAMIRA',
            'picture' => 'https://eboto.ph/uploads/2022/02/0fff8c9de460be7cff480c42c77ae13a.jpg',
            'profile_url' => 'https://eboto.ph/candidate/samiragutoc/issue-rundown',
            'party' => 'AKSYON DEMOKRATIKO',
            'ballot_number' => 32,
            'position' => 'senator',
        ],
        [
            'name' => 'HONASAN, GRINGO',
            'picture' => 'https://eboto.ph/uploads/2022/02/34029cb5abaccf1a645acfffe367db33.jpg',
            'profile_url' => 'https://eboto.ph/candidate/gregoriohonasan/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 33,
            'position' => 'senator',
        ],
        [
            'name' => 'HONTIVEROS, RISA',
            'picture' => 'https://eboto.ph/uploads/2022/02/d5ddf34d55953ed9c7f30a20fa915353.jpg',
            'profile_url' => 'https://eboto.ph/candidate/risahontiveros/issue-rundown?scrollto=candidate-info-tab',
            'party' => "AKBAYAN CITIZENS' ACTION PARTY",
            'ballot_number' => 34,
            'position' => 'senator',
        ],
        [
            'name' => 'JAVELLANA, RJ',
            'picture' => 'https://eboto.ph/uploads/2022/03/26b200daea7873cc71e7bdc4a246f20f.jpg',
            'profile_url' => 'https://eboto.ph/candidate/rj-javellana/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 35,
            'position' => 'senator',
        ],
        [
            'name' => 'KIRAM, NUR-MAHAL',
            'picture' => 'https://eboto.ph/uploads/2022/02/866d2fc98e80a314fde60af6007993cc.jpg',
            'profile_url' => 'https://eboto.ph/candidate/nur-mahal/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 36,
            'position' => 'senator',
        ],
        [
            'name' => 'LABOG, ELMER',
            'picture' => 'https://eboto.ph/uploads/2022/03/2e483fe14623ea194110bfb9667bb69c.jpg',
            'profile_url' => 'https://eboto.ph/candidate/elmer-labog/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'MAKABAYANG KOALISYON NG MAMAMAYAN',
            'ballot_number' => 37,
            'position' => 'senator',
        ],
        [
            'name' => 'LACSON, KUYA ALEX',
            'picture' => 'https://eboto.ph/uploads/2022/02/31dbbcd21e03ce0547c82a471e6e4caa.jpg',
            'profile_url' => 'https://eboto.ph/candidate/alexander-lacson/issue-rundown',
            'party' => 'KAPATIRAN PARTY',
            'ballot_number' => 38,
            'position' => 'senator',
        ],
        [
            'name' => 'LANGIT, REY',
            'picture' => 'https://eboto.ph/uploads/2022/02/f4da98b9aa4c409a7c6d30f22c4858de.jpg',
            'profile_url' => 'https://eboto.ph/candidate/reylangit/issue-rundown',
            'party' => 'PDP-LABAN',
            'ballot_number' => 39,
            'position' => 'senator',
        ],
        [
            'name' => 'LEGARDA, LOREN',
            'picture' => 'https://eboto.ph/uploads/2022/02/e473e7dacc2f59289ac283b8aa3de463.jpg',
            'profile_url' => 'https://eboto.ph/candidate/loren-legarda/issue-rundown?scrollto=candidate-info-tab',
            'party' => "NATIONALIST PEOPLE'S COALITION",
            'ballot_number' => 40,
            'position' => 'senator',
        ],
        [
            'name' => 'LIM, ARIEL',
            'picture' => 'https://eboto.ph/uploads/2022/02/46686a2dd87d1155a89dde7e16b6e7a2.jpg',
            'profile_url' => 'https://eboto.ph/candidate/ariel-lim/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 41,
            'position' => 'senator',
        ],
        [
            'name' => 'MALLILLIN, EMILY',
            'picture' => 'images/emily_mallillin.png',
            'profile_url' => 'https://news.tv5.com.ph/bilangpilipino/candidates/senator/mallillin-emily',
            'party' => 'PARTIDO PEDERAL NG MAHARLIKA',
            'ballot_number' => 42,
            'position' => 'senator',
        ],
        // [
        //     'name' => 'MARCOLETA, RODANTE',
        //     'picture' => 'https://eboto.ph/uploads/2022/02/2e8114b9a9864e051369eb9eb4ede7cc.JPG',
        //     'profile_url' => 'https://eboto.ph/candidate/rodante-marcoleta/issue-rundown?scrollto=candidate-info-tab',
        //     'party' => 'PDP-LABAN',
        //     'ballot_number' => 43,
        //     'position' => 'senator',
        // ],
        [
            'name' => 'MARCOS, FRANCIS LEO',
            'picture' => 'https://eboto.ph/uploads/2022/02/9e8dabf84db924bbe8ae0195d87cf0fb.jpg',
            'profile_url' => 'https://eboto.ph/candidate/francisleo-marcos/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 44,
            'position' => 'senator',
        ],
        [
            'name' => 'MATULA, SONNY',
            'picture' => 'https://eboto.ph/uploads/2022/02/6a4a9bb08d7139521deed9d2b8ad4307.jpg',
            'profile_url' => 'https://eboto.ph/candidate/matula/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 45,
            'position' => 'senator',
        ],
        [
            'name' => 'MINDALANO-ADAM, MARIETA',
            'picture' => 'https://eboto.ph/uploads/2022/03/1d0aec8043070ba82921edda7e8036b9.jpg',
            'profile_url' => 'https://eboto.ph/candidate/marieta-mindalano-adam/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'KATIPUNAN NG NAGKAKAISANG PILIPINO',
            'ballot_number' => 46,
            'position' => 'senator',
        ],
        [
            'name' => 'OLARTE, ATTY/DR. LEO',
            'picture' => 'https://pbs.twimg.com/profile_images/1449684714114019331/g9prJUKH_400x400.jpg',
            'profile_url' => 'https://eboto.ph/candidate/docleoolarte/issue-rundown',
            'party' => 'BIGKIS PINOY MOVEMENT',
            'ballot_number' => 47,
            'position' => 'senator',
        ],
        [
            'name' => 'PADILLA, DRA. MINGUITA',
            'picture' => 'images/minguita_padilla.png',
            'profile_url' => 'https://eboto.ph/candidate/minguita/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'PARTIDO PARA SA DEMOKRATIKONG REPORMA',
            'ballot_number' => 48,
            'position' => 'senator',
        ],
        [
            'name' => 'PADILLA, ROBIN',
            'picture' => 'https://eboto.ph/uploads/2022/02/2f063a8c72e388cc3b1eb26bb064b655.JPG',
            'profile_url' => 'https://eboto.ph/candidate/robinpadilla/issue-rundown',
            'party' => 'PDP-LABAN',
            'ballot_number' => 49,
            'position' => 'senator',
        ],
        [
            'name' => 'PANELO, SAL PANALO',
            'picture' => 'https://eboto.ph/uploads/2022/02/af603037971ac88686098928fb06c83d.jpg',
            'profile_url' => 'https://eboto.ph/candidate/sal-panelo/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'PDP-LABAN',
            'ballot_number' => 50,
            'position' => 'senator',
        ],
        [
            'name' => 'PIMENTEL, ASTRA',
            'picture' => 'https://eboto.ph/uploads/2022/02/5fb04cb8feb7fe9a6a9a8da36d895c9e.jpeg',
            'profile_url' => 'https://eboto.ph/candidate/astra-pimentel/issue-rundown',
            'party' => 'PDP-LABAN',
            'ballot_number' => 51,
            'position' => 'senator',
        ],
        [
            'name' => 'PIÑOL, MANNY',
            'picture' => 'https://eboto.ph/uploads/2022/02/943080df4e6bd8f0fb51615510b4524c.jpg',
            'profile_url' => 'https://eboto.ph/candidate/manny-fantin-pinol/issue-rundown?scrollto=candidate-info-tab',
            'party' => "NATIONALIST PEOPLE'S COALITION",
            'ballot_number' => 52,
            'position' => 'senator',
        ],
        [
            'name' => 'RICABLANCA, WILLIE JR.',
            'picture' => 'images/willie_ricablanca.png',
            'profile_url' => 'https://eboto.ph/candidate/willie-ricablanca/issue-rundown',
            'party' => 'PARTIDO MAHARLIKA',
            'ballot_number' => 53,
            'position' => 'senator',
        ],
        [
            'name' => 'ROQUE, HARRY SPOX',
            'picture' => 'https://eboto.ph/uploads/2022/02/5033b7ee668a439c6d40a3dffe9ea199.jpg',
            'profile_url' => 'https://eboto.ph/candidate/harry/issue-rundown?scrollto=candidate-info-tab',
            'party' => "PEOPLE'S REFORM PARTY",
            'ballot_number' => 54,
            'position' => 'senator',
        ],
        [
            'name' => 'SAHIDULLA, LADY ANNE',
            'picture' => 'images/ladyann_sahidulla.png',
            'profile_url' => 'https://eboto.ph/candidate/lady-anne-sahidulla/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'PEDERALISMO NG DUGONG DAKILANG SAMAHAN',
            'ballot_number' => 55,
            'position' => 'senator',
        ],
        [
            'name' => 'SISON, JOPET',
            'picture' => 'https://jopetsison.com/wp-content/uploads/2021/10/profile-pic-jopet-large.jpg',
            'profile_url' => 'https://eboto.ph/candidate/jopet-sison/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'AKSYON DEMOKRATIKO',
            'ballot_number' => 56,
            'position' => 'senator',
        ],
        [
            'name' => 'TEODORO, GIBO',
            'picture' => 'https://eboto.ph/uploads/2022/02/5430ed7143d3372abe074b5f0d6dbd30.JPG',
            'profile_url' => 'https://eboto.ph/candidate/gibo-cojuangco-teodoro/issue-rundown',
            'party' => "PEOPLE'S REFORM PARTY",
            'ballot_number' => 57,
            'position' => 'senator',
        ],
        [
            'name' => 'TRILLANES, ANTONIO IV',
            'picture' => 'https://eboto.ph/uploads/2022/02/c2b5bcabd3328fa62bc7822f7e193807.jpg',
            'profile_url' => 'https://eboto.ph/candidate/sonny-trillanes/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'LIBERAL PARTY',
            'ballot_number' => 58,
            'position' => 'senator',
        ],
        [
            'name' => 'TULFO, IDOL RAFFY',
            'picture' => 'https://eboto.ph/uploads/2022/02/1bdce4a040523e5a4c9dcf97af0cd0be.jpg',
            'profile_url' => 'https://eboto.ph/candidate/raffy-teshiba-tulfo/issue-rundown',
            'party' => 'INDEPENDENT',
            'ballot_number' => 59,
            'position' => 'senator',
        ],
        [
            'name' => 'VALEROS, REY',
            'picture' => 'https://eboto.ph/uploads/2022/03/a1996397f27557337acac19bdd12e684.jpg',
            'profile_url' => 'https://eboto.ph/candidate/reynaldo-valeros-jr/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 60,
            'position' => 'senator',
        ],
        [
            'name' => 'VILLANUEVA, JOEL TESDAMAN',
            'picture' => 'https://eboto.ph/uploads/2022/02/807718457e98406e1c6f4bee629d228b.jpg',
            'profile_url' => 'https://eboto.ph/candidate/joel-villanueva/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 61,
            'position' => 'senator',
        ],
        [
            'name' => 'VILLAR, MARK',
            'picture' => 'https://eboto.ph/uploads/2022/02/e09f2fe44666d17102098d14feb93526.jpg',
            'profile_url' => 'https://eboto.ph/candidate/markvillar/issue-rundown',
            'party' => 'NACIONALISTA PARTY',
            'ballot_number' => 62,
            'position' => 'senator',
        ],
        [
            'name' => 'ZUBIAGA, CARMEN',
            'picture' => 'images/carmen_zubiaga.png',
            'profile_url' => 'https://eboto.ph/candidate/carmen-zubiaga/issue-rundown?scrollto=candidate-info-tab',
            'party' => 'INDEPENDENT',
            'ballot_number' => 63,
            'position' => 'senator',
        ],
        [
            'name' => 'ZUBIRI, MIGZ',
            'picture' => 'https://eboto.ph/uploads/2022/02/8c6afacc7b2c3f34fbd7775f73854aab.jpg',
            'profile_url' => 'https://eboto.ph/candidate/juanmigzzubiri/issue-rundown',
            'party' => 'INDEPENDENT',
            'ballot_number' => 64,
            'position' => 'senator',
        ],
    ]
    
];